name: CSDMT
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
dependencies:
  - pytorch
  - torchvision
  - python=3.8.5
  - pip=20.3
  - numpy
  - cudatoolkit=11.0
  - xorg-libxrender
  - xorg-libxext
  - xorg-libsm
  - dlib=19.24
  - cmake[version='>=3.22']
